name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: git config --global user.name 'GitHub Actions' && git config --global user.email 'actions@github.com'

      # Create a new directory to store the gh-pages branch
      - name: Create gh-pages directory if not exists
        run: mkdir -p gh-pages

      # Clone the main branch into the gh-pages directory
      - name: Clone Repository to gh-pages branch
        run: git clone -b main --single-branch https://github.com/${{ github.repository }} gh-pages

      # Remove all files from the gh-pages branch (except .git directory)
      - name: Clean gh-pages directory
        run: |
          cd gh-pages
          shopt -s extglob
          rm -rf !(.git)


      # Commit and Push Changes to gh-pages branch
      - name: Commit and Push Changes
        run: |
          cd gh-pages
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push --force origin gh-pages
